-- Seed products
INSERT INTO products (id, name, category, price, description, images, dimensions, size_category, rooms, material, origin, stock) VALUES
  ('aaaaaaaa-0000-0000-0000-000000000001', 'Hereke Imperial Silk Rug', 'Handmade', 3850, 'A masterpiece of Turkish weaving from the imperial workshops of Hereke. This rug features a high knot density with pure silk threads, showcasing the classic "Seven Mountains" pattern.', ARRAY['https://placehold.co/1000x800', 'https://placehold.co/1000x800'], '4'' x 6''', 'Small', ARRAY['Bedroom', 'Office'], '100% Pure Silk', 'Hereke, Turkey', 1),
  ('aaaaaaaa-0000-0000-0000-000000000002', 'Antique Oushak Medallion', 'Vintage', 2450, 'A genuine vintage Oushak rug from the early 20th century. Known for its soft, muted palette and large-scale floral patterns, it brings a touch of history to any modern space.', ARRAY['https://placehold.co/1000x800', 'https://placehold.co/1000x800'], '9'' x 12''', 'Large', ARRAY['Living Room', 'Dining Room'], 'Hand-spun Wool', 'Uşak, Turkey', 1),
  ('aaaaaaaa-0000-0000-0000-000000000003', 'Anatolian Tribal Kilim', 'Kilim', 1200, 'Vibrant geometric patterns tell the story of Anatolian heritage. Each Kilim is unique, flat-woven by nomadic tribes using traditional techniques.', ARRAY['https://placehold.co/1000x800', 'https://placehold.co/1000x800'], '5'' x 7''', 'Medium', ARRAY['Living Room', 'Bedroom'], 'Hand-spun Wool', 'Anatolia, Turkey', 3),
  ('aaaaaaaa-0000-0000-0000-000000000004', 'Modern Machine-Woven Sultan', 'Machine', 450, 'A high-quality machine-woven rug that captures the essence of traditional Turkish designs. Durable, easy to clean, and perfect for high-traffic areas.', ARRAY['https://placehold.co/1000x800', 'https://placehold.co/1000x800'], '8'' x 10''', 'Large', ARRAY['Living Room', 'Dining Room', 'Hallway'], 'Heat-set Polypropylene', 'Gaziantep, Turkey', 15),
  ('aaaaaaaa-0000-0000-0000-000000000005', 'Vintage Isparta Floral', 'Vintage', 1850, 'A vintage Isparta rug featuring a dense floral field and a rich crimson border. These rugs are celebrated for their durability and classic Anatolian motifs.', ARRAY['https://placehold.co/1000x800'], '6'' x 9''', 'Medium', ARRAY['Living Room', 'Bedroom'], 'Wool on Cotton', 'Isparta, Turkey', 2),
  ('aaaaaaaa-0000-0000-0000-000000000006', 'Kayseri Silk-on-Silk Prayer Rug', 'Handmade', 2900, 'A fine Kayseri prayer rug, hand-knotted with silk on a silk foundation. The intricate mihrab design is a testament to the skill of Turkish artisans.', ARRAY['https://placehold.co/1000x800'], '3'' x 5''', 'Small', ARRAY['Bedroom', 'Office'], 'Pure Silk', 'Kayseri, Turkey', 1),
  ('aaaaaaaa-0000-0000-0000-000000000007', 'Machine-Woven Anatolian Runner', 'Machine', 180, 'A practical and stylish runner for your hallway. Features traditional Anatolian patterns in a modern, easy-care construction.', ARRAY['https://placehold.co/1000x800'], '2.5'' x 10''', 'Runner', ARRAY['Hallway'], 'Synthetic Blend', 'Gaziantep, Turkey', 20);

-- Seed product reviews
INSERT INTO product_reviews (product_id, user_name, rating, comment, date) VALUES
  ('aaaaaaaa-0000-0000-0000-000000000001', 'Sarah J.', 5, 'The silk detail is breathtaking. A true heirloom piece.', '2026-02-15'),
  ('aaaaaaaa-0000-0000-0000-000000000002', 'Michael R.', 5, 'The colors are beautifully faded. Exactly what I was looking for.', '2026-03-01'),
  ('aaaaaaaa-0000-0000-0000-000000000004', 'Emma L.', 4, 'Great quality for the price. Looks very similar to a handmade one.', '2026-01-20');

-- Seed blog posts
INSERT INTO blog_posts (id, title, excerpt, content, image, date, author, category, meta_description) VALUES
  ('bbbbbbbb-0000-0000-0000-000000000001', 'The Art of the Persian Knot: A History', 'Discover the centuries-old techniques that make Persian rugs the gold standard of textile artistry.', '<p>The Persian knot, also known as the Senneh knot, is a cornerstone of textile history. For centuries, artisans in the plateau of Iran have used this asymmetrical knot to create the most intricate and detailed designs known to man.</p><p>Unlike the symmetrical Turkish knot, the Persian knot allows for a higher knot density, enabling weavers to create fluid, curved lines and complex floral patterns that seem to dance across the wool or silk surface.</p><h3>The Technique</h3><p>A master weaver can tie up to 10,000 knots in a single day, but a high-quality Tabriz or Isfahan rug can contain millions of knots, meaning a single piece can take years to complete. This patience is what separates a true Persian masterpiece from a mass-produced imitation.</p><p>The process begins with the preparation of the loom, followed by the careful selection of hand-spun wool or silk, often dyed using natural vegetable extracts like madder root for reds, indigo for blues, and pomegranate skins for yellows.</p><blockquote>"Every knot is a silent prayer, a testament to a lineage of artistry that refuses to be forgotten in the age of machines."</blockquote><h3>Preserving the Heritage</h3><p>Today, we work directly with families in Tabriz and Isfahan to ensure these techniques are passed down. By choosing a hand-knotted Persian rug, you aren''t just buying a floor covering; you are becoming a custodian of a living history.</p>', 'https://placehold.co/1200x800', 'March 15, 2026', 'Amir Rahmani', 'Heritage', 'Explore the rich history of the Persian knot, its unique asymmetrical technique, and why it remains the gold standard in artisanal rug weaving.'),
  ('bbbbbbbb-0000-0000-0000-000000000002', 'How to Choose the Perfect Rug for Your Living Room', 'Size, material, and pattern—everything you need to know to find the foundation of your space.', '<p>Finding the right rug is like finding the soul of a room. It anchors the furniture, defines the space, and sets the emotional tone of your home.</p><h3>Size Matters</h3><p>The most common mistake is choosing a rug that is too small. In a living room, your rug should be large enough that at least the front legs of all major furniture pieces sit on it. This creates a sense of unity and prevents the "floating furniture" look.</p><h3>Material and Lifestyle</h3><p>If you have a high-traffic home with children or pets, a hand-knotted wool rug is your best friend. Wool is naturally stain-resistant and incredibly durable. For a formal space where elegance is the priority, a silk-blend rug offers a luminous sheen that changes with the light.</p><p>Consider the color palette of your walls and upholstery. A bold, geometric Kilim can add energy to a neutral room, while a faded Oushak provides a sense of calm and timelessness.</p>', 'https://placehold.co/1200x800', 'March 10, 2026', 'Elena Vance', 'Design', 'A comprehensive guide on selecting the right rug size, material, and style to anchor your living room and create a cohesive interior design.'),
  ('bbbbbbbb-0000-0000-0000-000000000003', 'Sustainable Weaving: The Future of Artisanal Rugs', 'How natural dyes and ethical sourcing are preserving both the environment and ancient cultures.', '<p>Sustainability isn''t a trend in the world of artisanal rugs; it''s the original way of making things. Before the industrial revolution, every rug was a product of its immediate environment.</p><h3>Natural Dyes</h3><p>We are seeing a massive resurgence in the use of vegetable dyes. These dyes are not only better for the environment but they also age more gracefully than chemical alternatives. They develop a "patina" over time, a subtle softening of color that collectors call ''abrash''.</p><h3>Ethical Sourcing</h3><p>True sustainability also means sustaining the people who make the art. We ensure fair wages and safe working conditions for all our artisan partners. This ethical foundation allows the craft to thrive and ensures that the next generation of weavers sees a future in their heritage.</p>', 'https://placehold.co/1200x800', 'March 05, 2026', 'Julian Thorne', 'Sustainability', 'Discover how the artisanal rug industry is leading the way in sustainability through natural dyes, ethical sourcing, and cultural preservation.');

-- Seed orders
INSERT INTO orders (id, status, date, items, estimated_delivery, location) VALUES
  ('ORD-12345', 'shipped', '2026-03-15', ARRAY['Tabriz Heritage Rug', 'Silk Road Runner'], '2026-03-22', 'In transit - Istanbul Hub'),
  ('ORD-67890', 'delivered', '2026-03-10', ARRAY['Modern Minimalist Grey'], '2026-03-14', 'Delivered - Front Porch'),
  ('ORD-55555', 'processing', '2026-03-19', ARRAY['Kilim Geometric Blue'], '2026-03-26', 'Preparing for shipment - Artisan Workshop');

-- Seed testimonials
INSERT INTO testimonials (name, location, title, text, date, rating, category) VALUES
  ('Sarah Jenkins', 'London, UK', 'Handmade Silk Rug review', 'The quality of the vintage Oushak I received is breathtaking. It completely transformed my client''s living space. The colors are even more vibrant in person. The craftsmanship is truly world-class.', 'October 21, 2025', 5, 'Handmade'),
  ('Michael Chen', 'New York, USA', 'Vintage Oushak review', 'A truly authentic piece of Anatolian history. The service was impeccable and the rug arrived perfectly packaged. Highly recommended for collectors who value heritage and quality.', 'November 12, 2025', 5, 'Vintage'),
  ('Emma Thompson', 'Sydney, AU', 'Modern Nomad review', 'I spent months looking for the right rug. Bisāṭ made it easy to find a piece that feels like it was made for our home. The texture is incredible and it feels so soft underfoot.', 'December 05, 2025', 5, 'Modern'),
  ('David Miller', 'Berlin, DE', 'Handmade Silk Rug review', 'The attention to detail is remarkable. You can tell this rug was made with love and patience. It''s not just a rug, it''s a piece of art that we will cherish for years.', 'January 15, 2026', 4, 'Handmade'),
  ('Elena Rossi', 'Milan, IT', 'Vintage Revival review', 'I was hesitant to buy such a large item online, but the team was so helpful with extra photos and videos. The rug is perfect and fits my space beautifully.', 'February 02, 2026', 5, 'Vintage'),
  ('James Wilson', 'Toronto, CA', 'Modern Nomad review', 'Excellent quality and fast shipping. The rug arrived in perfect condition. I love the minimalist design and the natural materials used.', 'March 10, 2026', 5, 'Modern');
